Notebook description: <br>

This notebook is created to analysis the kinematics data obtained after running the tracking code. <br>

Most of the tracking and analysis codes are written by Duncan and pieced together in this notebook. <br>

This one is specific to bout analysis (mapping and classification).

### Import experiment (tracked and with kinematics data).

In [1]:
from behavior_analysis.experiment import  BehaviorExperiment
import pandas as pd
# Open experiment
experiment = BehaviorExperiment.open(r"C:\Users\manyung.ng\Documents\behaviour_analysis\behavior_analysis_tracking\mafaa_analysis")
print(experiment)
# Open video and bout info
video_info = pd.read_csv(experiment.directory.joinpath('video_data.csv'), dtype={'ID': str, 'code': str})
bouts_df = pd.read_csv(experiment.subdirs["analysis"].joinpath('bouts.csv'),
                        dtype={'ID': str, 'code': str})

name: mafaa_analysis
date: 2025-06-30
animal_data: fish_data.csv
video_data: video_data.csv
mask_data: mask_data.csv
bout_detection: {'threshold': 0.03, 'winsize': 0.07}



### Data information

- Fish ID in the format 'YYYYMMDDNN' (year, month, day, zero-padded fish number; e.g. fish_1 on 2025_05_29 would be 20250529) <br>

- Video code in the format 'IDHHMMSS' (fish_ID, hour, minute, second) <br>

- Number of rows == number of frames in the video

#### Description of data in the "kinematics/code + .csv"
| Column name | Column data description |
| --- | --- |
| 'k0' - 'k(n-1)' | angle of tangents between n successive tail points |
| 'tip' | the average curvature (tail angle) over the last 20% of the tail|
| 'length' | the length of the tail (useful for finding tracking errors) |
| 'left' | the angle of the left eye relative to the heading |
| 'right' | the angle of the right eye relative to the heading |
| 'speed' | the instantaneous speed in each frame |
| 'angular_velocity' | the instantaneous angular velocity in each frame |
| 'tracked' | whether kinematic data exists from the frame |

## Bout mapping

In [2]:
from behavior_analysis.experiment import BehaviorExperiment
from behavior_analysis.analysis.bouts import BoutData
from behavior_analysis.analysis.bout_mapping import calculate_distance_matrix_templates, interpolate_nd
from behavior_analysis.utilities.timer import Timer
from behavior_analysis.utilities.manage_files_helpers import create_filepath
import pandas as pd
import numpy as np
from pathlib import Path
import os

In [3]:
if __name__ == "__main__":
    # Open template bouts
    template_directory = Path(r'J:\Duncan Mearns\behavior_mapping')
    template_frame_rate = 500.
    # Open 1744 exemplar bouts representative of all behaviors
    exemplars_df = pd.read_csv(template_directory.joinpath('exemplars.csv'),
                               dtype={'ID': str, 'code': str})
    # Open tail statistics and eigenfish for bout mapping
    eigenfish = np.load(template_directory.joinpath('eigenfish.npy'))
    eigenfish = eigenfish[:3]  # take first three eigenfish only
    mean, std = np.load(template_directory.joinpath('tail_statistics.npy'))
    # Import template bouts
    templates = BoutData.from_metadata(exemplars_df, template_directory.joinpath("kinematics"))
    # Map template bouts onto eigenfish
    templates = templates.map(vectors=eigenfish, whiten=True, mean=mean, std=std)
    templates = templates.to_list(values=True)
    print(len(templates))
    print(templates[0].shape)

Opening 681 csv files...
############ 10%
############ 20%
############ 30%
############ 40%
############ 50%
############ 60%
############ 70%
############ 80%
############ 90%
############ 100%
done!
DataFrame has shape: (20262060, 57).
Index levels: ('ID', 'code', 'frame').

Reformatting multi-indexed DataFrame... 

c:\Users\manyung.ng\Documents\behaviour_analysis\behavior_analysis_tracking\behavior_analysis\analysis\bouts.py:78: FutureWarning: inplace is deprecated and will be removed in a future version.
  data.index.set_levels(data.index.levels[2].astype('int64'), level='bout_index', inplace=True)


done!

1744
(82, 3)


In [73]:
if __name__ == "__main__":
    # Import bouts
    bouts = BoutData.from_metadata(bouts_df, experiment.subdirs["kinematics"], tail_only=True)
    # Map bouts onto eigenfish
    bouts = bouts.map(vectors=eigenfish, whiten=True, mean=mean, std=std)
    # Start timer
    timer = Timer()
    analysis_times = []
    timer.start()
    # distance matrix
    distances = {}
    # Iterate through fish
    output_directory = experiment.subdirs["analysis"].joinpath('bout_distances')
    if not output_directory.exists():
        output_directory.mkdir(parents=True)
    for ID in bouts.metadata['ID'].unique():
        # Save distance matrix for each fish to bout_distances folder in analysis directory
        output_path = output_directory.joinpath(ID + '.npy')
        path_exist = create_filepath(output_directory, ID, '.npy', True)
        # load distance matrix if the calculation is already performed.
        successful_indices = []  # Track which bouts we actually used
        if not output_path.exists():
            print(ID + '...', end=' ')
            # Interpolate bouts to correct frame rate
            fish_bouts = []
            for i, bout in bouts.iter(IDs=[ID], values=True):
                try:
                    code = bouts.metadata.loc[i, 'code']
                    fps = video_info[video_info['code'] == code].squeeze().fps
                    interp = interpolate_nd(bout, fps, template_frame_rate)
                    fish_bouts.append(interp)
                    successful_indices.append(i) # Track valid index -- gpt
                except Exception as e:
                    print(f'Skipping bout {i} due to error: {e}')
            # Calculate distance matrix
            D = calculate_distance_matrix_templates(fish_bouts, templates, fs=template_frame_rate)
            # Save distance matrix
            np.save(output_path, D)
            # Show time taken
            time_taken = timer.lap()
            analysis_times.append(time_taken)
            print(timer.convert_time(time_taken))
        if path_exist:
            distances[ID] = np.load(output_path)
            print('distance matrices loaded.')
    average_time = timer.average
    print(f'Total time: {timer.convert_time(timer.stop())}')
    print(f'Average time: {timer.convert_time(average_time)}')

Opening 96 csv files...
#################### 100%
done!
DataFrame has shape: (3601770, 57).
Index levels: ('ID', 'code', 'frame').

Reformatting multi-indexed DataFrame... 

c:\Users\manyung.ng\Documents\behaviour_analysis\behavior_analysis_tracking\behavior_analysis\analysis\bouts.py:78: FutureWarning: inplace is deprecated and will be removed in a future version.
  data.index.set_levels(data.index.levels[2].astype('int64'), level='bout_index', inplace=True)


done!

distance matrices loaded.
distance matrices loaded.
distance matrices loaded.
distance matrices loaded.
distance matrices loaded.
distance matrices loaded.
distance matrices loaded.
distance matrices loaded.
Total time: 0.24048781394958496 seconds
Average time: nan hours


c:\Users\manyung.ng\AppData\Local\anaconda3\envs\behavior_analysis\lib\site-packages\numpy\core\fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
c:\Users\manyung.ng\AppData\Local\anaconda3\envs\behavior_analysis\lib\site-packages\numpy\core\_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


In [177]:
if __name__ == "__main__":

    #################
    n_dims = 3
    frame_rate = 500.
    #################

    # note: somehow the indices of bouts.data and bouts.metadata don't line up (bout.data.index < bouts.metadata.index)
    # and exemplars cannot be mapped properly because of that
    # this should extract rows from bouts.metadata with the indices found in bouts.data
    valid_bout_indices = bouts.data.index.get_level_values('bout_index').unique()

    # Assign exemplars
    mapped_bouts = bouts.metadata.loc[bouts.metadata.index.isin(valid_bout_indices)].copy()
    mapped_bouts['exemplar'] = None
    for ID, fish_distances in distances.items():
        bout_idxs = mapped_bouts[mapped_bouts['ID'] == ID].index
        print(f"ID: {ID}")
        print(f"Number of bouts: {len(bout_idxs)}")
        print(f"Shape of fish_distances: {fish_distances.shape}")
        # if len(bout_idxs) != fish_distances.shape[0]:
        #     raise ValueError(f"Mismatch for ID {ID}: {len(bout_idxs)} bouts vs {fish_distances.shape[0]} distances")
        if len(bout_idxs) != fish_distances.shape[0]:
            print("Mismatch! Skipping this ID.")
            continue  # Skip or handle the mismatch case
        nearest_exemplar = np.argmin(fish_distances, axis=1)
        print(nearest_exemplar)
        mapped_bouts.loc[bout_idxs, 'exemplar'] = nearest_exemplar # crashes because length of bout_idxs does not match len of nearest_exemplar
        
    mapped_bouts.to_csv(os.path.join(experiment.subdirs['analysis'], 'mapped_bouts.csv'))


ID: 2025061201
Number of bouts: 2228
Shape of fish_distances: (2228, 1744)
[ 230  160  362 ... 1539 1278 1278]
ID: 2025061202
Number of bouts: 3028
Shape of fish_distances: (3028, 1744)
[  39  715  367 ...  791  497 1241]
ID: 2025061203
Number of bouts: 3935
Shape of fish_distances: (3935, 1744)
[1566 1732 1395 ... 1714  305 1208]
ID: 2025061204
Number of bouts: 3798
Shape of fish_distances: (3798, 1744)
[1431  377 1426 ...    6 1288 1576]
ID: 2025061205
Number of bouts: 3394
Shape of fish_distances: (3394, 1744)
[ 230  233  230 ... 1243  971  753]
ID: 2025061206
Number of bouts: 3117
Shape of fish_distances: (3117, 1744)
[1733  366  100 ...  644 1369 1302]
ID: 2025061207
Number of bouts: 3893
Shape of fish_distances: (3893, 1744)
[1047  866 1545 ...    6  224  235]
ID: 2025061208
Number of bouts: 4562
Shape of fish_distances: (4562, 1744)
[1252  295 1603 ... 1544  359  134]


In [178]:
mapped_bouts

,ID,code,start,end,exemplar
0,2025061201,2025061201134603.404,14,47,230
1,2025061201,2025061201134603.404,70,94,160
2,2025061201,2025061201134603.404,154,171,362
3,2025061201,2025061201134603.404,363,381,221
4,2025061201,2025061201134603.404,400,420,220
...,...,...,...,...,...
28088,2025061208,2025061208192132.138,36883,36923,1446
28089,2025061208,2025061208192132.138,36966,37011,1221
28090,2025061208,2025061208192132.138,37122,37174,1544
28091,2025061208,2025061208192132.138,37180,37374,359


trouble shooting chunk:

In [163]:
# Get all bout_index values present in bouts.data
available_bout_indices = (
    bouts.data.index.get_level_values('bout_index').unique()
)

# Get the expected bout indices from mapped_bouts
expected_bout_indices = bouts.metadata.index

# Find which expected bout indices are not present in the actual data
missing_indices = expected_bout_indices.difference(available_bout_indices)

print(f"Expected bouts (from metadata): {len(expected_bout_indices)}")
print(f"Available bouts (in bouts.data): {len(available_bout_indices)}")
print(f"⚠️ Missing bouts: {len(missing_indices)}")

# Show some missing examples
if not missing_indices.empty:
    print("\n🔍 Example missing bout(s):")
    display(bouts.metadata.loc[missing_indices[:5]])
else:
    print("✅ All metadata bouts are present in bouts.data.")


Expected bouts (from metadata): 28093
Available bouts (in bouts.data): 27955
⚠️ Missing bouts: 138

🔍 Example missing bout(s):


,ID,code,start,end
146,2025061201,2025061201134603.404,32147,32185
147,2025061201,2025061201134603.404,32187,32335
148,2025061201,2025061201134603.404,32426,32446
149,2025061201,2025061201134603.404,32574,32628
150,2025061201,2025061201134603.404,32649,32683


In [161]:
code = "2025061201134603.404"
subset = bouts.data.xs(code, level='code', drop_level=False)

print(f"Data shape for code {code}: {subset.shape}")
frame_range = subset.index.get_level_values('frame').unique()
print(f"Min frame: {frame_range.min()}, Max frame: {frame_range.max()}")


Data shape for code 2025061201134603.404: (7832, 3)
Min frame: 14, Max frame: 37517


## Behaviour analysis (Mearns et al., 2020)

In [11]:
from pathlib import Path
import numpy as np
import pandas as pd
from scipy.spatial import distance as ssd
from matplotlib import pyplot as plt

In [12]:
plt.rcParams["figure.dpi"] = 150

In [13]:
# set data path
data_path = Path(r"C:\Users\manyung.ng\Documents\behaviour_analysis\behavior_analysis_tracking\mafaa_analysis")

In [15]:
# import metadata
md = pd.read_csv(experiment.subdirs["analysis"].joinpath('bouts.csv'), dtype={'ID': str, 'code': str})

In [ ]:
md # still not the right md

,ID,code,start,end
0,2025061201,2025061201134603.404,14,47
1,2025061201,2025061201134603.404,70,94
2,2025061201,2025061201134603.404,154,171
3,2025061201,2025061201134603.404,363,381
4,2025061201,2025061201134603.404,400,420
...,...,...,...,...
28088,2025061208,2025061208192132.138,36883,36923
28089,2025061208,2025061208192132.138,36966,37011
28090,2025061208,2025061208192132.138,37122,37174
28091,2025061208,2025061208192132.138,37180,37374


In [ ]:
bout_md = md.loc[0]
bout_md

In [ ]:
trial_path = data_path.joinpath("kinematics", bout_md["ID"], bout_md["video_code"] + ".csv")
trial_kinematics = pd.read_csv(trial_path)